spring.application.name=Hospital-Management-System


spring.datasource.url=jdbc:mysql://mysql-5f4611f-unnatibhardwaj1729-c3f8.j.aivencloud.com:12695/hms?sslMode=REQUIRED&serverTimezone=Asia/Kolkata

spring.datasource.username=avnadmin

spring.datasource.password=AVNS_kXpkRE---DddRGh29vQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.thymeleaf.cache=false
spring.jpa.open-in-view=false

# Keep your custom port
server.port=8082